package deam.fsme.domain;
// Generated 12-Jan-2017 12:34:37 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IngredienteDeRecetaId generated by hbm2java
 */
@Embeddable
public class IngredienteDeRecetaId  implements java.io.Serializable {


     private int idIngrediente;
     private int idReceta;

    public IngredienteDeRecetaId() {
    }

    public IngredienteDeRecetaId(int idIngrediente, int idReceta) {
       this.idIngrediente = idIngrediente;
       this.idReceta = idReceta;
    }
   

    @Column(name="id_ingrediente", nullable=false)
    public int getIdIngrediente() {
        return this.idIngrediente;
    }
    
    public void setIdIngrediente(int idIngrediente) {
        this.idIngrediente = idIngrediente;
    }

    @Column(name="id_receta", nullable=false)
    public int getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(int idReceta) {
        this.idReceta = idReceta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IngredienteDeRecetaId) ) return false;
		 IngredienteDeRecetaId castOther = ( IngredienteDeRecetaId ) other; 
         
		 return (this.getIdIngrediente()==castOther.getIdIngrediente())
 && (this.getIdReceta()==castOther.getIdReceta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdIngrediente();
         result = 37 * result + this.getIdReceta();
         return result;
   }   


}


