package deam.fsme.domain;
// Generated 12-Jan-2017 12:34:37 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IngredienteDeReceta generated by hbm2java
 */
@Entity
@Table(name="ingrediente_de_receta"
    ,catalog="db_fsme"
)
public class IngredienteDeReceta  implements java.io.Serializable {


     private IngredienteDeRecetaId id;
     private Receta receta;
     private Ingrediente ingrediente;
     private int cantidad;

    public IngredienteDeReceta() {
    }

    public IngredienteDeReceta(IngredienteDeRecetaId id, Receta receta, Ingrediente ingrediente, int cantidad) {
       this.id = id;
       this.receta = receta;
       this.ingrediente = ingrediente;
       this.cantidad = cantidad;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idIngrediente", column=@Column(name="id_ingrediente", nullable=false) ), 
        @AttributeOverride(name="idReceta", column=@Column(name="id_receta", nullable=false) ) } )
    public IngredienteDeRecetaId getId() {
        return this.id;
    }
    
    public void setId(IngredienteDeRecetaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_receta", nullable=false, insertable=false, updatable=false)
    public Receta getReceta() {
        return this.receta;
    }
    
    public void setReceta(Receta receta) {
        this.receta = receta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ingrediente", nullable=false, insertable=false, updatable=false)
    public Ingrediente getIngrediente() {
        return this.ingrediente;
    }
    
    public void setIngrediente(Ingrediente ingrediente) {
        this.ingrediente = ingrediente;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


