package deam.fsme.domain;
// Generated 12-Jan-2017 12:34:37 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Receta generated by hbm2java
 */
@Entity
@Table(name="receta"
    ,catalog="db_fsme"
)
public class Receta  implements java.io.Serializable {


     private Integer idReceta;
     private TipoReceta tipoReceta;
     private String nombre;
     private int tiempo;
     private String preparacion;
     private String caracteristica;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<IngredienteDeReceta> ingredienteDeRecetas = new HashSet<IngredienteDeReceta>(0);

    public Receta() {
    }

	
    public Receta(TipoReceta tipoReceta, String nombre, int tiempo, String preparacion) {
        this.tipoReceta = tipoReceta;
        this.nombre = nombre;
        this.tiempo = tiempo;
        this.preparacion = preparacion;
    }
    public Receta(TipoReceta tipoReceta, String nombre, int tiempo, String preparacion, String caracteristica, Set<Usuario> usuarios, Set<IngredienteDeReceta> ingredienteDeRecetas) {
       this.tipoReceta = tipoReceta;
       this.nombre = nombre;
       this.tiempo = tiempo;
       this.preparacion = preparacion;
       this.caracteristica = caracteristica;
       this.usuarios = usuarios;
       this.ingredienteDeRecetas = ingredienteDeRecetas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_receta", unique=true, nullable=false)
    public Integer getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(Integer idReceta) {
        this.idReceta = idReceta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_receta", nullable=false)
    public TipoReceta getTipoReceta() {
        return this.tipoReceta;
    }
    
    public void setTipoReceta(TipoReceta tipoReceta) {
        this.tipoReceta = tipoReceta;
    }
    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="tiempo", nullable=false)
    public int getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(int tiempo) {
        this.tiempo = tiempo;
    }
    
    @Column(name="preparacion", nullable=false, length=500)
    public String getPreparacion() {
        return this.preparacion;
    }
    
    public void setPreparacion(String preparacion) {
        this.preparacion = preparacion;
    }
    
    @Column(name="caracteristica")
    public String getCaracteristica() {
        return this.caracteristica;
    }
    
    public void setCaracteristica(String caracteristica) {
        this.caracteristica = caracteristica;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="receta_de_usuario", catalog="db_fsme", joinColumns = { 
        @JoinColumn(name="id_receta", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_usuario", nullable=false, updatable=false) })
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="receta")
    public Set<IngredienteDeReceta> getIngredienteDeRecetas() {
        return this.ingredienteDeRecetas;
    }
    
    public void setIngredienteDeRecetas(Set<IngredienteDeReceta> ingredienteDeRecetas) {
        this.ingredienteDeRecetas = ingredienteDeRecetas;
    }




}


