package deam.fsme.domain;
// Generated 12-Jan-2017 12:34:37 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoReceta generated by hbm2java
 */
@Entity
@Table(name="tipo_receta"
    ,catalog="db_fsme"
)
public class TipoReceta  implements java.io.Serializable {


     private Integer idTipoReceta;
     private String nombre;
     private Set<Receta> recetas = new HashSet<Receta>(0);

    public TipoReceta() {
    }

	
    public TipoReceta(String nombre) {
        this.nombre = nombre;
    }
    public TipoReceta(String nombre, Set<Receta> recetas) {
       this.nombre = nombre;
       this.recetas = recetas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_tipo_receta", unique=true, nullable=false)
    public Integer getIdTipoReceta() {
        return this.idTipoReceta;
    }
    
    public void setIdTipoReceta(Integer idTipoReceta) {
        this.idTipoReceta = idTipoReceta;
    }
    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoReceta")
    public Set<Receta> getRecetas() {
        return this.recetas;
    }
    
    public void setRecetas(Set<Receta> recetas) {
        this.recetas = recetas;
    }




}


