package deam.fsme.domain;
// Generated 12-Jan-2017 12:34:37 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadDeMedida generated by hbm2java
 */
@Entity
@Table(name="unidad_de_medida"
    ,catalog="db_fsme"
)
public class UnidadDeMedida  implements java.io.Serializable {


     private Integer idUnidadMedida;
     private char nombre;
     private Set<Ingrediente> ingredientes = new HashSet<Ingrediente>(0);

    public UnidadDeMedida() {
    }

	
    public UnidadDeMedida(char nombre) {
        this.nombre = nombre;
    }
    public UnidadDeMedida(char nombre, Set<Ingrediente> ingredientes) {
       this.nombre = nombre;
       this.ingredientes = ingredientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_unidad_medida", unique=true, nullable=false)
    public Integer getIdUnidadMedida() {
        return this.idUnidadMedida;
    }
    
    public void setIdUnidadMedida(Integer idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }
    
    @Column(name="nombre", nullable=false, length=1)
    public char getNombre() {
        return this.nombre;
    }
    
    public void setNombre(char nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unidadDeMedida")
    public Set<Ingrediente> getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(Set<Ingrediente> ingredientes) {
        this.ingredientes = ingredientes;
    }




}


