package deam.fsme.domain;
// Generated 12-Jan-2017 12:34:37 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="db_fsme"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private Set<Receta> recetas = new HashSet<Receta>(0);

    public Usuario() {
    }

	
    public Usuario(String nombre) {
        this.nombre = nombre;
    }
    public Usuario(String nombre, Set<Receta> recetas) {
       this.nombre = nombre;
       this.recetas = recetas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Receta> getRecetas() {
        return this.recetas;
    }
    
    public void setRecetas(Set<Receta> recetas) {
        this.recetas = recetas;
    }




}


